[project]
name = "transcriptor"
version = "0.1.0"
description = ""
authors = [
    {name = "Jonnieey", email = "johnjahi55@gmail.com"},
]
dependencies = [
    "audioread~=2.1",
    "python-magic~=0.4",
    "appdirs~=1.4",
    "readchar~=3.0",
    "questionary~=1.10",
    "click~=8.0",
    
    "beautifultable~=1.0",
]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm.scripts]
transcriptor = {call = "transcriptor.main:main"}

[tool.pdm.dev-dependencies]
tests = [
    "pytest~=6.2",
    "black~=21.12b0",
    "isort~=5.10",
    "autoflake~=1.4",
]

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
include_trailing_comma = true

