[project]
name = "transcriptor"
version = "0.1.0"
description = ""
authors = [
    {name = "Jonnieey", email = "johnjahi55@gmail.com"},
]
dependencies = [
    "audioread~=2.1",
    "python-magic~=0.4",
    "whaaaaat~=0.5",
    "prompt-toolkit<2.0",
    "appdirs~=1.4",
]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest~=6.2",
]
