[metadata]
name = transcriptor
version = 0.1.0
author = Jonnieey
author_email = johnjahi55@gmail.com

[options]
packages = find:
package_dir = = src
include_package_data = True
python_requires = >= 3.6.2
install_requires =
    appdirs==1.4.4
    audioread==3.0.0
    click==8.1.2
    Jinja2==3.1.2
	markdownify==0.11.6
    python-magic==0.4.27
    PyYAML==6.0
	rich==13.3.1
    SQLAlchemy==2.0.0b2
    textual==0.10.1
    weasyprint==57.2
	cmd2==2.4.3
	prompt-toolkit==3.0.36

[options.extras_require]
dev = 
    black==22.10.0
    mypy==0.982
    pytest==7.2.0
    isort==5.10.1
    viztracer==0.15.4
    autoflake==2.0.0
	cmd2-ext-test==2.0.0

[options.packages.find]
where = src

[tool:pytest]
testpaths = tests
pythonpath = . src
filterwarnings =
    error
#filter unraisableexception
addopts = -p no:unraisableexception

[mypy]
files = transcriptor
warn_unused_configs = True
ignore_missing_imports = True
python_version = 3.10

[black]
line-length = 88

[isort]
line_length = 88
multi_line_output = 3
force_single_line = False
balanced_wrapping = True
include_trailing_comma = True

[mypy-importlib_metadata.*]
ignore_missing_imports = True

[options.entry_points]
console_scripts =
    trans3 = transcriptor.main:main
