"""Transcriptor database

Revision ID: 14b108a1a069
Revises:
Create Date: 2025-10-06 14:11:29.118879

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14b108a1a069"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("date_received", sa.String(), nullable=False),
        sa.Column("job_number", sa.String(), nullable=False),
        sa.Column("job_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("date_due", sa.String(), nullable=False),
        sa.Column("total_quantity", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("job_rate", sa.Float(), nullable=False),
        sa.Column("date_submitted", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=False),
        sa.Column("job_path", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("normal", sa.Float(), nullable=False),
        sa.Column("expedite", sa.Float(), nullable=False),
        sa.Column("interpreted", sa.Float(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Jobs",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("client_id", sa.INTEGER(), nullable=True),
        sa.Column("date_received", sa.DATE(), nullable=False),
        sa.Column("job_number", sa.VARCHAR(), nullable=False),
        sa.Column("job_type", sa.VARCHAR(), nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(),
            server_default=sa.text('("Pending")'),
            nullable=False,
        ),
        sa.Column("date_due", sa.DATE(), nullable=False),
        sa.Column("total_quantity", sa.FLOAT(), nullable=False),
        sa.Column("quantity", sa.FLOAT(), nullable=False),
        sa.Column("job_rate", sa.FLOAT(), nullable=False),
        sa.Column("date_submitted", sa.DATE(), nullable=True),
        sa.Column("amount", sa.FLOAT(), nullable=False),
        sa.Column(
            "amount_paid",
            sa.FLOAT(),
            server_default=sa.text("(0.0)"),
            nullable=False,
        ),
        sa.Column("job_path", sa.VARCHAR(length=100), nullable=False),
        sa.Column(
            "note",
            sa.VARCHAR(),
            server_default=sa.text('("")'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["Clients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Rates",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("normal", sa.FLOAT(), nullable=False),
        sa.Column("expedite", sa.FLOAT(), nullable=False),
        sa.Column("interpreted", sa.FLOAT(), nullable=False),
        sa.Column("client_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"], ["Clients.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Clients",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.drop_table("rates")
    op.drop_table("jobs")
    op.drop_table("clients")
    # ### end Alembic commands ###
